from pathlib import Path

FILES = [Path('NEW_DARK_RPG/index.html'), Path('android/app/src/main/assets/index.html')]

SHOP_OLD = '''<div id="shop" class="screen hidden"><div class="screen-title"><button class="back-mini" onclick="goBack()">← Назад</button><h2>Магазин</h2></div><div class="panel"><div class="gold" style="text-align:right">🪙 100</div><div class="tabs"><button>Оружие</button><button>Броня</button><button>Расходники</button><button>Прочее</button></div><div class="item"><div class="item-icon">🗡️</div><div>Железный меч<small>+2 к урону</small></div><b class="gold">50</b></div><div class="item"><div class="item-icon">🛡️</div><div>Кожаная броня<small>+2 к защите</small></div><b class="gold">40</b></div><div class="item"><div class="item-icon">🧪</div><div>Зелье здоровья<small>Восстанавливает 50 HP</small></div><b class="gold">25</b></div><div class="item"><div class="item-icon">🔵</div><div>Зелье маны<small>Восстанавливает 30 MP</small></div><b class="gold">25</b></div><button onclick="goBack()">Назад</button></div></div>'''
SHOP_NEW = '''<div id="shop" class="screen hidden"><div class="screen-title"><button class="back-mini" onclick="goBack()">← Назад</button><h2>Магазин</h2></div><div class="panel"><div class="gold" style="text-align:right">🪙 <b id="shopGold">100</b></div><div class="tabs"><button onclick="shopTab('weapon')">Оружие</button><button onclick="shopTab('armor')">Броня</button><button onclick="shopTab('consumable')">Расходники</button><button onclick="shopTab('other')">Прочее</button></div><div id="shopList"></div><button onclick="goBack()">Назад</button></div></div>'''
INV_OLD = '''<div id="inventory" class="screen hidden"><div class="screen-title"><button class="back-mini" onclick="goBack()">← Назад</button><h2>Инвентарь</h2></div><div class="panel"><div class="tabs"><button>Все</button><button>Оружие</button><button>Броня</button><button>Расходники</button></div><div id="inventoryList"></div><button onclick="goBack()">Назад</button></div></div>'''
INV_NEW = '''<div id="inventory" class="screen hidden"><div class="screen-title"><button class="back-mini" onclick="goBack()">← Назад</button><h2>Инвентарь</h2></div><div class="panel"><div class="tabs"><button onclick="inventoryTab('all')">Все</button><button onclick="inventoryTab('weapon')">Оружие</button><button onclick="inventoryTab('armor')">Броня</button><button onclick="inventoryTab('consumable')">Расходники</button></div><div id="inventoryList"></div><button onclick="goBack()">Назад</button></div></div>'''
SETTING_OLD = "function showSettings(){setScreen('settings')}"
SETTING_NEW = '''const settingOptions={graphics:['Высокое','Среднее','Низкое'],language:['Русский']};
function cycleSetting(type,button){const opts=settingOptions[type]||[];if(!opts.length)return;let current=localStorage.getItem('abyss_'+type)||opts[0];let i=opts.indexOf(current);i=(i+1)%opts.length;current=opts[i];localStorage.setItem('abyss_'+type,current);button.innerHTML='‹ '+current+' ›';if(el('out'))el('out').innerHTML='<span class="green">'+(type==='graphics'?'Графика':'Язык')+': '+current+'.</span>';sfx('click')}
function syncSettings(){document.querySelectorAll('#settings button').forEach(b=>{if(b.getAttribute('onclick')&&b.getAttribute('onclick').includes("cycleSetting('graphics'"))b.innerHTML='‹ '+(localStorage.getItem('abyss_graphics')||'Высокое')+' ›';if(b.getAttribute('onclick')&&b.getAttribute('onclick').includes("cycleSetting('language'"))b.innerHTML='‹ '+(localStorage.getItem('abyss_language')||'Русский')+' ›'})}
function showSettings(){syncSettings();setScreen('settings')}'''
RENDER_NEW = '''let inventoryCategory='all';
function inventoryType(name){const n=String(name).toLowerCase();if(n.includes('брон')||n.includes('щит'))return'armor';if(n.includes('зель')||n.includes('эликс')||n.includes('мана')||n.includes('здоров'))return'consumable';return'weapon'}
function inventoryTab(cat){inventoryCategory=cat;renderInventory()}
function renderInventory(){const source=hero.items.length?hero.items:[];let items=source.map((x,i)=>({name:x,icon:i%2?'🧪':'🗝️'}));if(!items.length)items=[{name:'Клинок тьмы',icon:'🗡️',fallback:'weapon'},{name:'Кожаная броня',icon:'🛡️',fallback:'armor'},{name:'Зелье здоровья',icon:'🧪',fallback:'consumable'},{name:'Зелье маны',icon:'🔵',fallback:'consumable'}];if(inventoryCategory!=='all')items=items.filter(x=>(x.fallback||inventoryType(x.name))===inventoryCategory);let list=items.map(x=>'<div class="item"><div class="item-icon">'+x.icon+'</div><div>'+x.name+'<small>Предмет из Бездны</small></div><b>×1</b></div>').join('');if(!list)list='<div class="muted" style="padding:10px;text-align:center">В этой категории пока нет предметов.</div>';if(el('inventoryList'))el('inventoryList').innerHTML=list}
'''

for path in FILES:
    s = path.read_text(encoding='utf-8')
    if SHOP_OLD in s:
        s = s.replace(SHOP_OLD, SHOP_NEW, 1)
    if "function showShop(){setScreen('shop')}" in s:
        s = s.replace("function showShop(){setScreen('shop')}", "function showShop(){shopTab('weapon');setScreen('shop')}\nconst shopItems=[{id:'sword',cat:'weapon',icon:'🗡️',name:'Железный меч',desc:'+2 к урону',price:50},{id:'armor',cat:'armor',icon:'🛡️',name:'Кожаная броня',desc:'+2 к защите',price:40},{id:'hp',cat:'consumable',icon:'🧪',name:'Зелье здоровья',desc:'Восстанавливает 50 HP',price:25},{id:'mp',cat:'consumable',icon:'🔵',name:'Зелье маны',desc:'Восстанавливает 30 MP',price:25}];\nlet shopCategory='weapon';\nfunction shopTab(cat){shopCategory=cat;const list=el('shopList');if(!list)return;const items=shopItems.filter(x=>x.cat===cat);if(cat==='other'){list.innerHTML='<div class=\"item\"><div class=\"item-icon\">🔑</div><div>Таинственный ключ<small>Редкий предмет</small></div><b class=\"gold\">75</b></div>';if(el('shopGold'))el('shopGold').textContent=getGold();return;}list.innerHTML=items.map(x=>'<button class=\"item shop-item\" style=\"text-align:left;display:grid;width:100%\" onclick=\"buyItem(\\''+x.id+'\\')\"><div class=\"item-icon\">'+x.icon+'</div><div>'+x.name+'<small>'+x.desc+'</small></div><b class=\"gold\">'+x.price+'</b></button>').join('');if(el('shopGold'))el('shopGold').textContent=getGold()}\nfunction getGold(){return Number(localStorage.getItem('abyss_gold')||100)}\nfunction setGold(v){localStorage.setItem('abyss_gold',String(Math.max(0,v)));if(el('shopGold'))el('shopGold').textContent=getGold()}\nfunction buyItem(id){const item=shopItems.find(x=>x.id===id);if(!item)return;const gold=getGold();if(gold<item.price){sfx('error');if(el('out'))el('out').innerHTML='<span class=\"red\">Недостаточно золота.</span>';return;}setGold(gold-item.price);if(item.cat==='weapon')hero.attack+=2;if(item.cat==='armor')hero.def+=2;if(item.id==='hp')hero.items.push('Зелье здоровья');if(item.id==='mp')hero.items.push('Зелье маны');save();update();sfx('buy');if(el('out'))el('out').innerHTML='<span class=\"green\">Куплено: '+item.name+'.</span>';shopTab(shopCategory)}", 1)
    if INV_OLD in s:
        s = s.replace(INV_OLD, INV_NEW, 1)
    s = s.replace('<span>Графика</span><button>‹ Высокое ›</button>', '<span>Графика</span><button onclick="cycleSetting(\'graphics\',this)">‹ Высокое ›</button>', 1)
    s = s.replace('<span>Язык</span><button>‹ Русский ›</button>', '<span>Язык</span><button onclick="cycleSetting(\'language\',this)">‹ Русский ›</button>', 1)
    if "function escapeBattle(){sfx('back');history.back()}" in s:
        s = s.replace("function escapeBattle(){sfx('back');history.back()}", "function escapeBattle(){goBack()}", 1)
    if 'function renderInventory(){' in s and 'let inventoryCategory=' not in s:
        start = s.find('function renderInventory(){')
        end = s.find('function renderEquipment()', start)
        s = s[:start] + RENDER_NEW + s[end:]
    if SETTING_OLD in s:
        s = s.replace(SETTING_OLD, SETTING_NEW, 1)
    s = s.replace("save();update();history.replaceState({screen:'main'},'','#main');setScreen('main',false);return}", "save();update();screenHistory=['menu','main'];history.replaceState({screen:'main'},'','#main');setScreen('main',false);return}", 1)
    s = s.replace("function mainMenu(){closeModal();history.replaceState({screen:'menu'},'','#menu');setScreen('menu',false)}", "function mainMenu(){closeModal();screenHistory=['menu'];history.replaceState({screen:'menu'},'','#menu');setScreen('menu',false)}", 1)
    s = s.replace("screenHistory=['menu'];screenHistory=['menu'];history.replaceState", "screenHistory=['menu'];history.replaceState", 1)
    path.write_text(s, encoding='utf-8')
