from pathlib import Path
import re

CSS = r'''.hero-panel{padding:10px}.hero-progress{display:grid;grid-template-columns:1fr 1fr;gap:7px}.hero-progress .info-card{padding:7px}.hero-equipment-title,.hero-available-title{text-align:center;color:#b22;font:11px monospace;letter-spacing:2px;margin:10px 0 6px}.hero-equipment{display:grid;grid-template-columns:1fr 1.05fr 1fr;gap:6px;align-items:center}.hero-equip-side{display:grid;gap:6px}.hero-equip-card{min-height:72px;padding:5px;border:1px solid #4d9b55;background:linear-gradient(#0b160c,#070907);box-shadow:0 0 8px rgba(80,190,90,.12);display:grid;grid-template-columns:32px 1fr;grid-template-rows:auto auto;column-gap:5px;align-items:center;font-size:20px}.hero-equip-card b{font:11px Georgia;color:#ddd;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.hero-equip-card small{grid-column:2;color:#77db70;font:9px monospace}.hero-equip-card button{grid-column:1/3;min-height:27px;padding:3px;font-size:10px;margin:2px 0 0}.hero-equip-card.empty{border-color:#4b1515;background:#080808;box-shadow:none;opacity:.72;display:flex;flex-direction:column;justify-content:center;text-align:center;gap:2px}.hero-equip-card.empty b{font-size:10px}.hero-equip-card.empty small{font-size:9px;color:#777}.hero-figure{height:232px;display:grid;place-items:center;font-size:120px;background:radial-gradient(circle,#250b0c,transparent 58%);filter:drop-shadow(0 0 14px #700)}.hero-stats-box{margin-top:7px;padding:9px;border:1px solid #721515;background:#070707;font:12px monospace;line-height:1.65}.hero-actions{display:grid;grid-template-columns:1fr 1fr;gap:6px}.hero-actions button{margin:5px 0}.hero-available{display:grid;grid-template-columns:43px 1fr auto;gap:7px;align-items:center;padding:7px;border:1px solid #421010;background:#080808;margin:4px 0;font-size:11px}.hero-available button{width:auto;min-width:76px;min-height:31px;margin:0;padding:4px 7px;font-size:10px}.hero-available small{display:block;color:#888;margin-top:2px}@media(max-width:360px){.hero-figure{height:190px;font-size:95px}.hero-equip-card{min-height:66px}.hero-equip-card b{font-size:9px}}'''

HERO_RE = re.compile(r'<div id="hero" class="screen hidden">.*?(?=<div id="shop" class="screen hidden">)', re.S)
HERO_NEW = '''<div id="hero" class="screen hidden"><div class="screen-title"><button class="back-mini" onclick="goBack()">← Назад</button><h2>Герой</h2></div><div class="panel hero-panel"><div class="hero-progress"><div class="info-card"><div class="info-row"><span>Уровень</span><b id="heroLevel">1</b></div><div class="bar gold"><i id="heroLevelBar"></i></div></div><div class="info-card"><div class="info-row"><span>Опыт</span><b id="heroXp">0/100</b></div><div class="bar gold"><i id="heroXpBar"></i></div></div></div><div class="hero-equipment-title">ЭКИПИРОВКА</div><div class="hero-equipment"><div class="hero-equip-side"><div class="hero-equip-card" id="heroWeaponCard"></div><div class="hero-equip-card empty">🪖<b>Голова</b><small>— Пусто</small></div><div class="hero-equip-card empty">💍<b>Кольцо</b><small>— Пусто</small></div></div><div class="hero-figure">🧍</div><div class="hero-equip-side"><div class="hero-equip-card" id="heroArmorCard"></div><div class="hero-equip-card empty">🧥<b>Плащ</b><small>— Пусто</small></div><div class="hero-equip-card empty">👢<b>Обувь</b><small>— Пусто</small></div></div></div><div class="hero-stats-box" id="heroStats"></div><div class="hero-actions"><button onclick="levelUp()">Улучшить</button><button onclick="unequipAll()">Снять всё</button></div><div class="hero-available-title">ДОСТУПНЫЕ ПРЕДМЕТЫ</div><div id="heroAvailableItems"></div><button onclick="goBack()">Назад</button></div></div>
'''

RENDER_RE = re.compile(r"function renderHero\(\)\{.*?\nfunction levelUp", re.S)
RENDER_NEW = '''function renderHero(){if(!el('heroStats'))return;const xpNeed=100;el('heroLevel').textContent=hero.level;el('heroXp').textContent=hero.xp+'/'+xpNeed;el('heroXpBar').style.width=Math.min(100,hero.xp/xpNeed*100)+'%';el('heroLevelBar').style.width='100%';el('heroStats').innerHTML='❤️ HP: '+hero.hp+'/'+hero.maxHp+' &nbsp; 💧 MP: '+hero.energy+'/'+hero.maxEnergy+'<br>⚔️ Сила: '+hero.attack+' &nbsp; 🛡️ Защита: '+hero.def+'<br>◆ Уровень: '+hero.level+' &nbsp; ◆ Класс: '+(hero.class||'—')+'<br>🪙 Золото: '+getGold()+' &nbsp; ◆ Крит. шанс: '+Math.round(hero.crit*100)+'%<br>◆ Навык: '+((classStats[hero.class]||{}).skill||'—');renderHeroEquipment()}
function heroEquipCard(id,slot,icon,name,type){const node=el(id);if(!node)return;const equipped=name&&name!=='Нет';node.className='hero-equip-card'+(equipped?'':' empty');if(!equipped){node.innerHTML=icon+'<b>'+slot+'</b><small>— НЕ ЭКИПИРОВАНО</small>';return}node.innerHTML=`${icon}<b>${name}</b><small>✓ ЭКИПИРОВАНО</small><button onclick="unequipItemType('${type}')">Снять</button>`}
function renderHeroEquipment(){heroEquipCard('heroWeaponCard','Оружие','⚔️',hero.weapon||'Нет','weapon');heroEquipCard('heroArmorCard','Броня','🛡️',hero.armor||'Нет','armor');const list=el('heroAvailableItems');if(!list)return;const available=[];hero.items.forEach((raw,index)=>{const x=itemInfo(raw);if((x.type==='weapon'||x.type==='armor')&&((x.type==='weapon'&&x.name!==hero.weapon)||(x.type==='armor'&&x.name!==hero.armor)))available.push({x,index})});list.innerHTML=available.length?available.map(({x,index})=>'<div class="hero-available"><div class="item-icon">'+x.icon+'</div><div>'+x.name+'<small>'+(x.type==='weapon'?'+2 к атаке':'+2 к защите')+' · НЕ ЭКИПИРОВАНО</small></div><button onclick="useInventoryItem('+index+')">Надеть</button></div>').join(''):'<div class="muted" style="padding:8px;text-align:center">Нет других оружия или брони.</div>'}
function unequipItemType(type){if(type==='weapon'&&hero.weapon&&hero.weapon!=='Нет'){const old=itemInfo({name:hero.weapon});hero.attack-=Number(old.attack||2);hero.weapon='Нет'}if(type==='armor'&&hero.armor&&hero.armor!=='Нет'){const old=itemInfo({name:hero.armor});hero.def-=Number(old.def||2);hero.armor='Нет'}sfx('back');logEvent('ЭКИПИРОВКА','Предмет снят.');save();update();renderHero();renderEquipment()}
function unequipAll(){if(hero.weapon&&hero.weapon!=='Нет')unequipItemType('weapon');if(hero.armor&&hero.armor!=='Нет')unequipItemType('armor')}
function levelUp'''

def patch(path):
    p=Path(path)
    s=p.read_text()
    if '.hero-panel{' not in s:
        s=s.replace('</style>', CSS+'</style>', 1)
    s,n=HERO_RE.subn(HERO_NEW,s,count=1)
    if n!=1:
        raise SystemExit(f'hero markup patch failed: {path}')
    s,n=RENDER_RE.subn(RENDER_NEW,s,count=1)
    if n!=1:
        raise SystemExit(f'hero js patch failed: {path}')
    p.write_text(s)

for path in ['NEW_DARK_RPG/index.html','android/app/src/main/assets/index.html']:
    patch(path)
print('Hero equipment screen patched.')
