from pathlib import Path
import re

HERO_ART = "data:image/jpeg;base64,__B64__"

CSS = r''' 
.hero-v34{padding:10px 8px 12px;background:linear-gradient(180deg,rgba(15,0,0,.88),rgba(3,3,3,.98));border:1px solid #9a1515;box-shadow:0 0 18px rgba(180,0,0,.2),inset 0 0 18px rgba(130,0,0,.12)}
.hero-v34 .hero-progress{display:grid;grid-template-columns:1fr 1fr;gap:7px;margin-bottom:10px}.hero-v34 .hero-progress .info-card{padding:7px 8px;border:1px solid #6d1717;background:#050505}.hero-v34 .hero-progress .info-row{font-size:14px}.hero-v34 .hero-progress .bar{height:6px;margin-top:5px}.hero-v34 .hero-progress .bar i{background:#e9aa24;box-shadow:0 0 7px #e9aa24}
.hero-v34 .hero-stage{position:relative;display:grid;grid-template-columns:1fr 1.05fr 1fr;gap:6px;min-height:420px;padding:7px 0 4px;overflow:hidden}.hero-v34 .hero-stage:before{content:"";position:absolute;inset:0;background:radial-gradient(circle at 50% 42%,rgba(220,0,0,.48),transparent 38%),radial-gradient(circle at 67% 13%,rgba(255,35,10,.65),transparent 9%),linear-gradient(180deg,#150507,#28070b 45%,#050506 100%);border:1px solid #3e1010}.hero-v34 .hero-stage:after{content:"";position:absolute;left:50%;top:7%;width:66px;height:66px;transform:translateX(18%);border-radius:50%;background:#080808;box-shadow:0 0 0 6px rgba(220,0,0,.12),0 0 30px 12px rgba(210,0,0,.35);opacity:.9}
.hero-v34 .hero-equip-side{position:relative;z-index:3;display:grid;align-content:start;gap:6px}.hero-v34 .hero-equip-card{min-height:82px;padding:5px 6px;border:1px solid #555;background:linear-gradient(#090909,#050505);display:grid;grid-template-columns:44px 1fr;grid-template-rows:auto auto auto;column-gap:6px;align-items:center;box-shadow:inset 0 0 8px rgba(255,255,255,.025)}.hero-v34 .hero-equip-card.equipped{border:2px solid #00f06a;background:linear-gradient(90deg,#06140b,#050807);box-shadow:0 0 10px rgba(0,240,106,.28),inset 0 0 10px rgba(0,220,100,.08)}.hero-v34 .hero-equip-card .gear-icon{grid-row:1/4;width:42px;height:54px;display:grid;place-items:center;border:1px solid #555;background:radial-gradient(circle,#161616,#050505);font-size:25px}.hero-v34 .hero-equip-card.equipped .gear-icon{border:2px solid #00e96a}.hero-v34 .hero-equip-card b{font:12px Georgia,"Times New Roman",serif;color:#eee;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.hero-v34 .hero-equip-card small{font:10px monospace;color:#aaa}.hero-v34 .hero-equip-card.equipped small{color:#00ef72;font-weight:bold}.hero-v34 .hero-equip-card button{grid-column:2;min-height:26px;margin:2px 0 0;padding:2px 5px;font-size:10px;border-color:#8d1a1a}.hero-v34 .hero-equip-card.empty{opacity:.9}.hero-v34 .hero-equip-card.empty small{color:#777}.hero-v34 .hero-equip-card.empty button{border-color:#2f4b69;background:#141c27;color:#c2d0df}
.hero-v34 .hero-figure{position:relative;z-index:2;height:420px;display:flex;align-items:flex-end;justify-content:center;overflow:hidden;background:radial-gradient(ellipse at 50% 50%,rgba(120,0,0,.28),transparent 58%)}.hero-v34 .hero-figure .hero-art{height:98%;width:auto;max-width:150%;object-fit:contain;mix-blend-mode:screen;filter:contrast(1.05) saturate(.95) drop-shadow(0 0 10px rgba(220,0,0,.45));transform:translateY(3%)}
.hero-v34 .hero-stats-box{margin-top:7px;padding:9px 8px;border:1px solid #9a1515;background:#050505;display:grid;grid-template-columns:1fr 1fr 1fr;gap:0;font:11px Georgia,"Times New Roman",serif;line-height:1.75}.hero-v34 .hero-stats-box>div{padding:0 8px;border-right:1px solid #391313}.hero-v34 .hero-stats-box>div:last-child{border-right:0}.hero-v34 .hero-stat{display:flex;gap:5px;align-items:center;white-space:nowrap}.hero-v34 .hero-stat .ico{font-size:18px}.hero-v34 .hero-stat .val{color:#eee}.hero-v34 .hero-actions{display:grid;grid-template-columns:1fr 1fr;gap:7px;margin-top:8px}.hero-v34 .hero-actions button{min-height:43px;margin:0;font-size:15px;border-color:#a71b1b}.hero-v34 .hero-bottom-tabs{display:grid;grid-template-columns:repeat(5,1fr);margin-top:8px;border:1px solid #5d1414;background:#050505}.hero-v34 .hero-bottom-tabs button{min-height:61px;margin:0;border:0;border-right:1px solid #271010;border-radius:0;background:linear-gradient(#080808,#030303);font-size:10px;color:#aaa;padding:4px}.hero-v34 .hero-bottom-tabs button:last-child{border-right:0}.hero-v34 .hero-bottom-tabs button b{display:block;font-size:21px;color:#777;margin-bottom:4px}.hero-v34 .hero-bottom-tabs button.active{color:#f22;background:linear-gradient(#170707,#080404);box-shadow:inset 0 0 14px rgba(240,0,0,.22)}.hero-v34 .hero-bottom-tabs button.active b{color:#f22}
@media(max-width:390px){.hero-v34 .hero-stage{min-height:360px}.hero-v34 .hero-figure{height:360px}.hero-v34 .hero-equip-card{min-height:70px;grid-template-columns:36px 1fr}.hero-v34 .hero-equip-card .gear-icon{width:34px;height:48px;font-size:20px}.hero-v34 .hero-equip-card b{font-size:10px}.hero-v34 .hero-equip-card small{font-size:8px}.hero-v34 .hero-stats-box{font-size:9px}.hero-v34 .hero-stat .ico{font-size:15px}.hero-v34 .hero-bottom-tabs button{font-size:8px;min-height:56px}}
'''

HERO_RE = re.compile(r'<div id="hero" class="screen hidden">.*?(?=<div id="shop" class="screen hidden">)', re.S)
HERO_NEW = r'''<div id="hero" class="screen hidden"><div class="screen-title"><button class="back-mini" onclick="goBack()">← Назад</button><h2>Герой</h2></div><div class="panel hero-v34"><div class="hero-progress"><div class="info-card"><div class="info-row"><span>Уровень</span><b id="heroLevel">1</b></div><div class="bar gold"><i id="heroLevelBar"></i></div></div><div class="info-card"><div class="info-row"><span>Опыт</span><b id="heroXp">0/1000</b></div><div class="bar gold"><i id="heroXpBar"></i></div></div></div><div class="hero-stage"><div class="hero-equip-side"><div class="hero-equip-card" id="heroWeaponCard"></div><div class="hero-equip-card empty"><div class="gear-icon">🪖</div><b>Голова</b><small>+1 Защиты</small><button disabled>Надеть</button></div><div class="hero-equip-card empty"><div class="gear-icon">💍</div><b>Кольцо</b><small>—</small><button disabled>Надеть</button></div><div class="hero-equip-card empty"><div class="gear-icon">👢</div><b>Обувь</b><small>—</small><button disabled>Надеть</button></div></div><div class="hero-figure"><img class="hero-art" alt="" src="__HERO_ART__"></div><div class="hero-equip-side"><div class="hero-equip-card" id="heroArmorCard"></div><div class="hero-equip-card empty"><div class="gear-icon">🧥</div><b>Плащ</b><small>+1 Защиты</small><button disabled>Надеть</button></div><div class="hero-equip-card empty"><div class="gear-icon">🔮</div><b>Амулет</b><small>—</small><button disabled>Надеть</button></div><div class="hero-equip-card empty"><div class="gear-icon">🛡️</div><b>Щит</b><small>—</small><button disabled>Надеть</button></div></div></div><div class="hero-stats-box" id="heroStats"></div><div class="hero-actions"><button onclick="unequipAll()">Снять всё</button><button onclick="goBack()">Назад</button></div><div class="hero-bottom-tabs"><button class="active" onclick="showHero()"><b>♙</b>Герой</button><button onclick="showInventory()"><b>♧</b>Инвентарь</button><button onclick="showEquipment()"><b>⚔</b>Экипировка</button><button onclick="showHero()"><b>▥</b>Статы</button><button onclick="showHero()"><b>♨</b>Навыки</button></div></div></div>'''

RENDER_RE = re.compile(r"function renderHero\(\)\{.*?\nfunction levelUp", re.S)
RENDER_NEW = r'''function renderHero(){if(!el('heroStats'))return;const xpNeed=1000;el('heroLevel').textContent=hero.level;el('heroXp').textContent=hero.xp+'/'+xpNeed;el('heroXpBar').style.width=Math.min(100,hero.xp/xpNeed*100)+'%';el('heroLevelBar').style.width='100%';el('heroStats').innerHTML='<div><div class="hero-stat"><span class="ico">❤️</span><span>HP:</span><span class="val">'+hero.hp+'/'+hero.maxHp+'</span></div><div class="hero-stat"><span class="ico">💧</span><span>MP:</span><span class="val">'+hero.energy+'/'+hero.maxEnergy+'</span></div><div class="hero-stat"><span class="ico">⚔️</span><span>Сила:</span><span class="val">'+hero.attack+'</span></div></div><div><div class="hero-stat"><span class="ico">🛡️</span><span>Защита:</span><span class="val">'+hero.def+'</span></div><div class="hero-stat"><span class="ico">◆</span><span>Уровень:</span><span class="val">'+hero.level+'</span></div><div class="hero-stat"><span class="ico">★</span><span>Класс:</span><span class="val">'+(hero.class||'—')+'</span></div></div><div><div class="hero-stat"><span class="ico">🪙</span><span>Золото:</span><span class="val">'+getGold()+'</span></div><div class="hero-stat"><span class="ico">◆</span><span>Крит. шанс:</span><span class="val">'+Math.round(hero.crit*100)+'%</span></div><div class="hero-stat"><span class="ico">🥾</span><span>Навык:</span><span class="val">'+((classStats[hero.class]||{}).skill||'—')+'</span></div></div>';renderHeroEquipment()}
function heroEquipCard(id,slot,icon,name,type){const node=el(id);if(!node)return;const equipped=name&&name!=='Нет';node.className='hero-equip-card'+(equipped?' equipped':'');if(!equipped){node.innerHTML='<div class="gear-icon">'+icon+'</div><b>'+slot+'</b><small>— НЕ ЭКИПИРОВАНО</small><button disabled>Надеть</button>';return}const info=itemInfo({name:name});const bonus=type==='weapon'?('+'+Number(info.attack||2)+' Атаки'):('+'+Number(info.def||2)+' Защиты');node.innerHTML='<div class="gear-icon">'+icon+'</div><b>'+name+'</b><small>✓ ЭКИПИРОВАНО · '+bonus+'</small><button onclick="unequipItemType(\''+type+'\')">Снять</button>'}
function renderHeroEquipment(){heroEquipCard('heroWeaponCard','Оружие','⚔️',hero.weapon||'Нет','weapon');heroEquipCard('heroArmorCard','Броня','🛡️',hero.armor||'Нет','armor')}
function unequipItemType(type){if(type==='weapon'&&hero.weapon&&hero.weapon!=='Нет'){const old=itemInfo({name:hero.weapon});hero.attack-=Number(old.attack||2);hero.weapon='Нет'}if(type==='armor'&&hero.armor&&hero.armor!=='Нет'){const old=itemInfo({name:hero.armor});hero.def-=Number(old.def||2);hero.armor='Нет'}sfx('back');logEvent('ЭКИПИРОВКА','Предмет снят.');save();update();renderHero();renderEquipment()}
function unequipAll(){if(hero.weapon&&hero.weapon!=='Нет')unequipItemType('weapon');if(hero.armor&&hero.armor!=='Нет')unequipItemType('armor')}
function levelUp'''

def patch(path):
    p=Path(path)
    s=p.read_text()
    s=s.replace('</style>',CSS+'</style>',1) if '.hero-v34{' not in s else s
    s,n=HERO_RE.subn(HERO_NEW.replace('__HERO_ART__',HERO_ART),s,count=1)
    if n!=1: raise SystemExit(f'hero markup patch failed: {path}')
    s,n=RENDER_RE.subn(RENDER_NEW,s,count=1)
    if n!=1: raise SystemExit(f'hero js patch failed: {path}')
    p.write_text(s)

for path in ('NEW_DARK_RPG/index.html','android/app/src/main/assets/index.html'):
    patch(path)
print('Hero v3.4 screen applied.')
