from pathlib import Path
import re

# Экран Героя делаем по референсу: 4 слота слева, 4 справа, персонаж по центру,
# нижняя статистика и нижняя навигация. Вся существующая игровая логика экипировки сохраняется.
CSS = r'''
/* === ГЕРОЙ: РЕФЕРЕНСНЫЙ МОБИЛЬНЫЙ ЭКРАН === */
.hero-ref{width:min(100%,780px);box-sizing:border-box;margin:0 auto;padding:10px 10px 12px;background:linear-gradient(180deg,#120304 0%,#070606 58%,#030303 100%);border:2px solid #8d1717;box-shadow:0 0 22px rgba(150,0,0,.22),inset 0 0 22px rgba(120,0,0,.14);overflow:hidden}
.hero-ref .hero-progress{display:grid;grid-template-columns:1fr 1fr;gap:16px;margin:0 0 18px}
.hero-ref .hero-progress .info-card{height:104px;box-sizing:border-box;padding:12px 14px;border:2px solid #671b1b;background:#060606}
.hero-ref .hero-progress .info-row{font:22px Georgia,"Times New Roman",serif;color:#ddd;display:flex;justify-content:space-between;align-items:center;margin-bottom:12px}
.hero-ref .hero-progress .info-row b{font-size:27px;color:#eee}
.hero-ref .hero-progress .bar{height:10px;border:2px solid #3b1717;background:#170808;margin:0}
.hero-ref .hero-progress .bar i{display:block;height:100%;background:#e9ad26;box-shadow:0 0 5px #e9ad26}
.hero-ref .hero-stage{position:relative;display:grid;grid-template-columns:1fr 1.05fr 1fr;gap:18px;min-height:650px;padding:14px 0 10px;border:2px solid #361313;background:linear-gradient(180deg,#0c0405,#160507 50%,#050505 100%);box-sizing:border-box}
.hero-ref .hero-stage:before{content:"";position:absolute;inset:0;background:radial-gradient(circle at 50% 43%,rgba(210,0,0,.42),transparent 34%),radial-gradient(circle at 68% 13%,rgba(255,40,10,.7),transparent 8%),linear-gradient(180deg,transparent,#080303 80%);pointer-events:none}
.hero-ref .hero-stage:after{content:"";position:absolute;left:50%;top:45px;width:110px;height:110px;transform:translateX(-18%);border-radius:50%;background:#070707;box-shadow:0 0 0 8px rgba(190,0,0,.10),0 0 35px 15px rgba(210,0,0,.25);pointer-events:none}
.hero-ref .hero-equip-side{position:relative;z-index:3;display:grid;grid-template-rows:repeat(4,1fr);gap:12px;min-width:0}
.hero-ref .hero-equip-card{height:138px;box-sizing:border-box;padding:10px 10px;border:2px solid #565656;background:linear-gradient(180deg,#090909,#050505);display:grid;grid-template-columns:76px 1fr;grid-template-rows:auto auto auto;column-gap:10px;align-items:center;box-shadow:inset 0 0 12px rgba(255,255,255,.02)}
.hero-ref .hero-equip-card.equipped{border-color:#00e875;background:linear-gradient(90deg,#06130a,#050807);box-shadow:0 0 12px rgba(0,235,105,.22),inset 0 0 12px rgba(0,220,100,.08)}
.hero-ref .gear-icon{grid-row:1/4;width:74px;height:104px;display:grid;place-items:center;box-sizing:border-box;border:2px solid #555;background:radial-gradient(circle,#171717,#050505);font-size:43px}
.hero-ref .equipped .gear-icon{border-color:#00e875}
.hero-ref .hero-equip-card b{font:19px Georgia,"Times New Roman",serif;color:#eee;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
.hero-ref .hero-equip-card small{font:16px Georgia,"Times New Roman",serif;color:#777;white-space:nowrap}
.hero-ref .hero-equip-card.equipped small{color:#00ee73;font-weight:bold}
.hero-ref .hero-equip-card button{grid-column:2;min-height:44px;margin:2px 0 0;padding:4px 8px;border:2px solid #a32121;border-radius:10px;background:linear-gradient(#171010,#090707);color:#eee;font:18px Georgia,"Times New Roman",serif}
.hero-ref .hero-equip-card.empty button{border-color:#314866;background:#141a24;color:#bfc9d7}
.hero-ref .hero-equip-card button:disabled{opacity:1}
.hero-ref .hero-figure{position:relative;z-index:2;height:600px;display:flex;align-items:center;justify-content:center;overflow:visible;background:radial-gradient(ellipse at 50% 55%,rgba(145,0,0,.38),transparent 58%)}
.hero-ref .hero-art-svg{width:100%;height:88%;overflow:visible;filter:drop-shadow(0 0 12px rgba(210,0,0,.52))}
.hero-ref .hero-stats-box{margin-top:16px;padding:12px 12px;border:2px solid #8d1717;background:#050505;display:grid;grid-template-columns:1fr 1fr 1fr;gap:0;font:17px Georgia,"Times New Roman",serif;line-height:1.95;overflow:hidden}
.hero-ref .hero-stats-box>div{padding:0 12px;border-right:2px solid #321414;min-width:0}
.hero-ref .hero-stats-box>div:last-child{border-right:0}
.hero-ref .hero-stat{display:flex;align-items:center;gap:8px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
.hero-ref .hero-stat .ico{font-size:25px;flex:0 0 auto}.hero-ref .hero-stat .val{color:#eee;overflow:hidden;text-overflow:ellipsis}
.hero-ref .hero-actions{display:grid;grid-template-columns:1fr 1fr;gap:16px;margin-top:16px}.hero-ref .hero-actions button{min-height:74px;margin:0;border:2px solid #a32121;border-radius:13px;background:linear-gradient(#171010,#080707);font:25px Georgia,"Times New Roman",serif;color:#eee}
.hero-ref .hero-bottom-tabs{display:grid;grid-template-columns:repeat(5,1fr);margin-top:16px;border:2px solid #551313;background:#050505}
.hero-ref .hero-bottom-tabs button{min-height:116px;margin:0;border:0;border-right:2px solid #241010;border-radius:0;background:#050505;color:#999;font:15px Georgia,"Times New Roman",serif;padding:8px 3px}
.hero-ref .hero-bottom-tabs button:last-child{border-right:0}.hero-ref .hero-bottom-tabs button b{display:block;font-size:34px;color:#777;margin-bottom:10px}.hero-ref .hero-bottom-tabs button.active{color:#e52a2a;background:linear-gradient(#160606,#080404);box-shadow:inset 0 0 20px rgba(230,0,0,.18)}.hero-ref .hero-bottom-tabs button.active b{color:#ef2a2a}
@media(max-width:700px){.hero-ref{padding:7px 6px 8px}.hero-ref .hero-progress{gap:8px;margin-bottom:9px}.hero-ref .hero-progress .info-card{height:74px;padding:8px}.hero-ref .hero-progress .info-row{font-size:15px;margin-bottom:6px}.hero-ref .hero-progress .info-row b{font-size:19px}.hero-ref .hero-progress .bar{height:7px}.hero-ref .hero-stage{grid-template-columns:1fr .95fr 1fr;gap:6px;min-height:510px;padding:7px 0}.hero-ref .hero-stage:after{width:70px;height:70px;top:32px}.hero-ref .hero-equip-side{gap:7px}.hero-ref .hero-equip-card{height:112px;padding:6px;grid-template-columns:46px 1fr;column-gap:5px}.hero-ref .gear-icon{width:44px;height:82px;font-size:28px}.hero-ref .hero-equip-card b{font-size:14px}.hero-ref .hero-equip-card small{font-size:11px}.hero-ref .hero-equip-card button{min-height:34px;font-size:14px;border-radius:8px}.hero-ref .hero-figure{height:500px}.hero-ref .hero-stats-box{margin-top:8px;padding:8px;font-size:11px;line-height:1.7}.hero-ref .hero-stats-box>div{padding:0 6px}.hero-ref .hero-stat{gap:4px}.hero-ref .hero-stat .ico{font-size:17px}.hero-ref .hero-actions{gap:8px;margin-top:8px}.hero-ref .hero-actions button{min-height:52px;font-size:19px}.hero-ref .hero-bottom-tabs{margin-top:8px}.hero-ref .hero-bottom-tabs button{min-height:76px;font-size:10px}.hero-ref .hero-bottom-tabs button b{font-size:24px;margin-bottom:5px}}
@media(max-width:390px){.hero-ref .hero-stage{gap:3px}.hero-ref .hero-equip-card{height:92px;grid-template-columns:38px 1fr}.hero-ref .gear-icon{width:36px;height:68px;font-size:23px}.hero-ref .hero-equip-card b{font-size:11px}.hero-ref .hero-equip-card small{font-size:9px}.hero-ref .hero-equip-card button{min-height:28px;font-size:11px}.hero-ref .hero-figure{height:410px}.hero-ref .hero-stats-box{font-size:9px}.hero-ref .hero-stat .ico{font-size:14px}.hero-ref .hero-bottom-tabs button{font-size:8px;min-height:64px}}
'''

ART = r'''<svg class="hero-art-svg" viewBox="0 0 220 430" aria-hidden="true"><defs><linearGradient id="hrc" x1="0" y1="0" x2="1" y2="1"><stop stop-color="#070809"/><stop offset=".55" stop-color="#24272a"/><stop offset="1" stop-color="#050506"/></linearGradient><linearGradient id="hrm"><stop stop-color="#686a6d"/><stop offset=".35" stop-color="#16181a"/><stop offset=".7" stop-color="#45484b"/><stop offset="1" stop-color="#090a0b"/></linearGradient><linearGradient id="hrr"><stop stop-color="#3a0407"/><stop offset=".5" stop-color="#ef101c"/><stop offset="1" stop-color="#350407"/></linearGradient><filter id="hrg"><feGaussianBlur stdDeviation="3" result="b"/><feMerge><feMergeNode in="b"/><feMergeNode in="SourceGraphic"/></feMerge></filter></defs><ellipse cx="110" cy="407" rx="72" ry="14" fill="#65070b" opacity=".7" filter="url(#hrg)"/><path d="M52 408Q35 350 54 268L72 204Q76 164 82 124Q110 100 138 124Q144 164 148 204L166 268Q185 350 168 408Z" fill="url(#hrc)" stroke="#44484c" stroke-width="3"/><path d="M78 126Q110 96 142 126L134 175Q110 193 86 175Z" fill="#030405" stroke="#777b80" stroke-width="2"/><path d="M87 127Q110 108 133 127L128 151Q110 165 92 151Z" fill="#000"/><path d="M77 164L56 190L72 226L92 199L94 175ZM143 164L164 190L148 226L128 199L126 175Z" fill="url(#hrm)" stroke="#0a0b0c" stroke-width="2"/><path d="M88 173L110 184L132 173L140 214L110 228L80 214Z" fill="#202326" stroke="#777b80" stroke-width="2"/><path d="M110 184L110 222M88 196L132 196" stroke="#08090a" stroke-width="3"/><path d="M84 213L72 255L92 266L104 230ZM136 213L148 255L128 266L116 230Z" fill="url(#hrm)" stroke="#08090a" stroke-width="2"/><path d="M92 264L76 334L96 382L110 338L110 264ZM128 264L144 334L124 382L110 338L110 264Z" fill="#141618" stroke="#666a6e" stroke-width="2"/><path d="M76 333L62 408L92 408L105 349ZM144 333L158 408L128 408L115 349Z" fill="#08090a" stroke="#3f4144" stroke-width="2"/><path d="M84 214L110 226L136 214L132 240L110 249L88 240Z" fill="url(#hrr)" opacity=".9"/><circle cx="110" cy="233" r="5" fill="#ff2430" filter="url(#hrg)"/><path d="M171 286L202 397" stroke="#d2d5d8" stroke-width="7"/><path d="M176 284L205 397" stroke="#34373a" stroke-width="3"/><path d="M165 278L183 294L174 302L158 286Z" fill="#8e1018"/></svg>'''

HERO = '''<div id="hero" class="screen hidden"><div class="screen-title"><button class="back-mini" onclick="goBack()">← Назад</button><h2>Герой</h2></div><div class="panel hero-ref"><div class="hero-progress"><div class="info-card"><div class="info-row"><span>Уровень</span><b id="heroLevel">1</b></div><div class="bar gold"><i id="heroLevelBar"></i></div></div><div class="info-card"><div class="info-row"><span>Опыт</span><b id="heroXp">0/1000</b></div><div class="bar gold"><i id="heroXpBar"></i></div></div></div><div class="hero-stage"><div class="hero-equip-side"><div class="hero-equip-card" id="heroWeaponCard"></div><div class="hero-equip-card empty"><div class="gear-icon">🪖</div><b>Голова</b><small>+1 Защиты</small><button disabled>Надеть</button></div><div class="hero-equip-card empty"><div class="gear-icon">💍</div><b>Кольцо</b><small>—</small><button disabled>Надеть</button></div><div class="hero-equip-card empty"><div class="gear-icon">👢</div><b>Обувь</b><small>—</small><button disabled>Надеть</button></div></div><div class="hero-figure">__ART__</div><div class="hero-equip-side"><div class="hero-equip-card" id="heroArmorCard"></div><div class="hero-equip-card empty"><div class="gear-icon">🧥</div><b>Плащ</b><small>+1 Защиты</small><button disabled>Надеть</button></div><div class="hero-equip-card empty"><div class="gear-icon">🔮</div><b>Амулет</b><small>—</small><button disabled>Надеть</button></div><div class="hero-equip-card empty"><div class="gear-icon">🛡️</div><b>Щит</b><small>—</small><button disabled>Надеть</button></div></div></div><div class="hero-stats-box" id="heroStats"></div><div class="hero-actions"><button onclick="unequipAll()">Снять всё</button><button onclick="goBack()">Назад</button></div><div class="hero-bottom-tabs"><button class="active" onclick="heroRefNav('hero')"><b>♙</b>Герой</button><button onclick="heroRefNav('inventory')"><b>♧</b>Инвентарь</button><button onclick="heroRefNav('equipment')"><b>⚔</b>Экипировка</button><button onclick="heroRefNav('hero')"><b>▥</b>Статы</button><button onclick="heroRefNav('hero')"><b>♨</b>Навыки</button></div></div></div>'''.replace('__ART__', ART)

RENDER = r'''function renderHero(){if(!el('heroStats'))return;const xpNeed=1000;el('heroLevel').textContent=hero.level;el('heroXp').textContent=hero.xp+'/'+xpNeed;el('heroXpBar').style.width=Math.min(100,hero.xp/xpNeed*100)+'%';el('heroLevelBar').style.width='100%';el('heroStats').innerHTML='<div><div class="hero-stat"><span class="ico">❤️</span><span>HP:</span><span class="val">'+hero.hp+'/'+hero.maxHp+'</span></div><div class="hero-stat"><span class="ico">💧</span><span>MP:</span><span class="val">'+hero.energy+'/'+hero.maxEnergy+'</span></div><div class="hero-stat"><span class="ico">⚔️</span><span>Сила:</span><span class="val">'+hero.attack+'</span></div></div><div><div class="hero-stat"><span class="ico">🛡️</span><span>Защита:</span><span class="val">'+hero.def+'</span></div><div class="hero-stat"><span class="ico">◆</span><span>Уровень:</span><span class="val">'+hero.level+'</span></div><div class="hero-stat"><span class="ico">★</span><span>Класс:</span><span class="val">'+(hero.class||'—')+'</span></div></div><div><div class="hero-stat"><span class="ico">🪙</span><span>Золото:</span><span class="val">'+getGold()+'</span></div><div class="hero-stat"><span class="ico">◆</span><span>Крит. шанс:</span><span class="val">'+Math.round((hero.crit||0)*100)+'%</span></div><div class="hero-stat"><span class="ico">🥾</span><span>Навык:</span><span class="val">'+((classStats[hero.class]||{}).skill||'—')+'</span></div></div>';renderHeroEquipment()}
function renderHeroEquipment(){const w=el('heroWeaponCard'),a=el('heroArmorCard');if(w){const on=hero.weapon&&hero.weapon!=='Нет';w.className='hero-equip-card'+(on?' equipped':' empty');w.innerHTML=on?'<div class="gear-icon">⚔️</div><b>'+hero.weapon+'</b><small>✓ ЭКИПИРОВАНО</small><button onclick="unequipItemType(\'weapon\')">Снять</button>':'<div class="gear-icon">⚔️</div><b>Оружие</b><small>— НЕ ЭКИПИРОВАНО</small><button disabled>Надеть</button>'}if(a){const on=hero.armor&&hero.armor!=='Нет';a.className='hero-equip-card'+(on?' equipped':' empty');a.innerHTML=on?'<div class="gear-icon">🛡️</div><b>'+hero.armor+'</b><small>✓ ЭКИПИРОВАНО</small><button onclick="unequipItemType(\'armor\')">Снять</button>':'<div class="gear-icon">🛡️</div><b>Броня</b><small>— НЕ ЭКИПИРОВАНО</small><button disabled>Надеть</button>'}}
function heroRefNav(id){document.querySelectorAll('.screen').forEach(s=>s.classList.add('hidden'));const target=el(id);if(target)target.classList.remove('hidden');if(id==='hero')renderHero();if(id==='inventory'&&typeof renderInventory==='function')renderInventory();if(id==='equipment'&&typeof renderEquipment==='function')renderEquipment();}
function levelUp'''

RE_HERO = re.compile(r'<div id="hero" class="screen hidden">.*?(?=<div id="shop" class="screen hidden">)', re.S)
RE_RENDER = re.compile(r'function renderHero\(\)\{.*?\nfunction levelUp', re.S)

def patch(path):
    p=Path(path)
    s=p.read_text()
    if '/* === ГЕРОЙ: РЕФЕРЕНСНЫЙ МОБИЛЬНЫЙ ЭКРАН === */' not in s:
        s=s.replace('</style>',CSS+'</style>',1)
    s,n=RE_HERO.subn(HERO+'\n',s,count=1)
    if n!=1: raise SystemExit(f'Hero markup not found: {path}')
    s,n=RE_RENDER.subn(RENDER,s,count=1)
    if n!=1: raise SystemExit(f'Hero render function not found: {path}')
    p.write_text(s)

for f in ('NEW_DARK_RPG/index.html','android/app/src/main/assets/index.html'):
    patch(f)
print('Reference Hero screen patched.')
