/* RELEASE-V3.8 — только согласованные задачи 2–6. */
(function(){
  function gearDefaults(){return {head:'Нет',ring:'Нет',boots:'Нет',cloak:'Нет',amulet:'Нет',shield:'Нет'}}
  function ensureGear(){hero.gear=hero.gear&&typeof hero.gear==='object'?hero.gear:gearDefaults();Object.keys(gearDefaults()).forEach(k=>{if(!hero.gear[k])hero.gear[k]='Нет'})}
  const __normalizeHero=normalizeHero; normalizeHero=function(){const ok=__normalizeHero.apply(this,arguments);ensureGear();return ok}; ensureGear();
  const __save=save; save=function(){ensureGear();localStorage.setItem('abyss_gear',JSON.stringify(hero.gear));localStorage.setItem('abyss_key_caches',JSON.stringify(abyssKeyCaches||{}));return __save.apply(this,arguments)};
  const __loadGame=loadGame; loadGame=function(){const ok=__loadGame.apply(this,arguments);try{const g=JSON.parse(localStorage.getItem('abyss_gear')||'null');if(g&&typeof g==='object')hero.gear=g;const c=JSON.parse(localStorage.getItem('abyss_key_caches')||'null');if(c&&typeof c==='object')abyssKeyCaches=c}catch(e){}ensureGear();return ok};
  function depthBest(){return Math.max(1,Number(localStorage.getItem('chronicles_abyss_infinite_best_v1')||abyssFloor||1))}
  function refreshDepthSelector(){const q=el('depthSelect');if(!q)return;const best=depthBest();q.innerHTML='';for(let d=1;d<=best;d++){const o=document.createElement('option');o.value=d;o.textContent='Глубина '+d;o.selected=d===Number(abyssFloor);q.appendChild(o)}if(el('bestDepthValue'))el('bestDepthValue').textContent=best}
  function selectAbyssDepth(){const q=el('depthSelect');const d=Math.max(1,Math.min(depthBest(),Number(q&&q.value||1)));abyssFloor=d;abyssRoom=0;abyssBossDefeated=false;abyssRoomContent='Новая комната ещё не исследована.';save();updateAbyss();logEvent('ГЛУБИНА','Выбрана глубина '+d+'.')}
  window.selectAbyssDepth=selectAbyssDepth; window.refreshDepthSelector=refreshDepthSelector;
  const __updateAbyss=updateAbyss; updateAbyss=function(){__updateAbyss.apply(this,arguments);refreshDepthSelector();const d=Math.max(1,Number(abyssFloor||1));const hasKey=hero&&hero.items&&hero.items.some(x=>itemInfo(x).name==='Таинственный ключ');const opened=!!(abyssKeyCaches&&abyssKeyCaches[d]);if(el('abyssKeyBtn'))el('abyssKeyBtn').style.display=hasKey&&!opened?'block':'none'};
  const __showAbyss=showAbyss; showAbyss=function(){__showAbyss.apply(this,arguments);refreshDepthSelector();updateAbyss()};
  window.openAbyssKeyCache=function(){const i=hero.items.findIndex(x=>itemInfo(x).name==='Таинственный ключ');const d=Math.max(1,Number(abyssFloor||1));if(i<0)return;if(abyssKeyCaches[d])return;hero.items.splice(i,1);const gold=50+d*8;hero.gold+=gold;const loot=generateLoot();const added=addItemToInventory(loot);abyssKeyCaches[d]=true;sfx('open');logEvent('ТАЙНИК','Открыт запечатанный тайник глубины '+d+'. +'+gold+' золота.'+(added?' Предмет: '+loot.name+'.':' Инвентарь заполнен — предмет не получен.'));save();update();updateAbyss()};
  const __generateLoot=generateLoot; generateLoot=function(){const r=Math.random();if(r<.12)return {name:'Стальной шлем',type:'head',slot:'head',icon:'🪖',def:2};if(r<.22)return {name:'Серебряное кольцо',type:'ring',slot:'ring',icon:'💍',crit:.03};if(r<.32)return {name:'Плащ странника',type:'cloak',slot:'cloak',icon:'🧥',def:1};if(r<.42)return {name:'Сапоги пустоши',type:'boots',slot:'boots',icon:'👢',def:1};if(r<.52)return {name:'Амулет Бездны',type:'amulet',slot:'amulet',icon:'🔮',maxEnergy:8};if(r<.62)return {name:'Щит пепла',type:'shield',slot:'shield',icon:'🛡️',def:3};return __generateLoot.apply(this,arguments)};
  function gearInfo(item){return item&&typeof item==='object'?item:itemInfo(item)}
  const __equipItem=equipItem; equipItem=function(index,item){ensureGear();if(!['head','ring','boots','cloak','amulet','shield'].includes(item.type))return __equipItem.apply(this,arguments);const slot=item.slot||item.type;const oldName=hero.gear[slot]||'Нет';if(oldName!=='Нет'){const old=gearInfo({name:oldName});hero.def=Math.max(0,hero.def-Number(old.def||0));hero.crit=Math.max(0,hero.crit-Number(old.crit||0));hero.maxEnergy=Math.max(1,hero.maxEnergy-Number(old.maxEnergy||0))}hero.gear[slot]=item.name;hero.def+=Number(item.def||0);hero.crit=Math.min(1,hero.crit+Number(item.crit||0));hero.maxEnergy+=Number(item.maxEnergy||0);hero.energy=Math.min(hero.maxEnergy,hero.energy+Number(item.maxEnergy||0));save()};
  const __useInventoryItem=useInventoryItem; useInventoryItem=function(index){const item=hero.items[index];if(item&&['head','ring','boots','cloak','amulet','shield'].includes(item.type)){equipItem(index,item);sfx('buy');logEvent('ЭКИПИРОВКА','Экипировано: '+item.name+'.');save();update();renderInventory();return}return __useInventoryItem.apply(this,arguments)};
  const __unequipItemType=unequipItemType; unequipItemType=function(type){ensureGear();if(!['head','ring','boots','cloak','amulet','shield'].includes(type))return __unequipItemType.apply(this,arguments);const name=hero.gear[type];if(!name||name==='Нет')return;const old=gearInfo({name});hero.def=Math.max(0,hero.def-Number(old.def||0));hero.crit=Math.max(0,hero.crit-Number(old.crit||0));hero.maxEnergy=Math.max(1,hero.maxEnergy-Number(old.maxEnergy||0));hero.energy=Math.min(hero.energy,hero.maxEnergy);hero.gear[type]='Нет';save();update();renderHero();renderEquipment();renderInventory();logEvent('ЭКИПИРОВКА','Снято: '+name+'.')};
  const __unequipAll=unequipAll; unequipAll=function(){ensureGear();__unequipAll.apply(this,arguments);Object.keys(hero.gear).forEach(k=>{hero.gear[k]='Нет'});save();update();renderHero();renderEquipment();renderInventory()};
  const __renderEquipment=renderEquipment; renderEquipment=function(){ensureGear();__renderEquipment.apply(this,arguments);const map={head:['equipHead','🪖'],ring:['equipRing','💍'],boots:['equipBoots','👢'],cloak:['equipBody','🧥']};Object.keys(map).forEach(k=>{const n=el(map[k][0]);if(!n)return;const name=hero.gear[k]||'Нет';n.dataset.slot=k;n.innerHTML='<div>'+map[k][1]+'</div><div class="equip-name">'+(name==='Нет'?'Пусто':name)+'</div><div class="equip-state">'+(name==='Нет'?'— НЕ ЭКИПИРОВАНО':'✓ ЭКИПИРОВАНО')+'</div>'})};
  const __renderHeroEquipment=renderHeroEquipment; renderHeroEquipment=function(){ensureGear();__renderHeroEquipment.apply(this,arguments);const cards={head:['heroHeadCard','🪖','Голова'],ring:['heroRingCard','💍','Кольцо'],boots:['heroBootsCard','👢','Обувь'],cloak:['heroCloakCard','🧥','Плащ'],amulet:['heroAmuletCard','🔮','Амулет'],shield:['heroShieldCard','🛡️','Щит']};Object.keys(cards).forEach(k=>{const c=cards[k],n=el(c[0]);if(!n)return;const name=hero.gear[k]||'Нет';n.className='hero-equip-card '+(name==='Нет'?'empty':'equipped');n.innerHTML=name==='Нет'?'<div class="gear-icon">'+c[1]+'</div><b>'+c[2]+'</b><small>— НЕ ЭКИПИРОВАНО</small><button disabled>Надеть</button>':'<div class="gear-icon">'+c[1]+'</div><b>'+name+'</b><small>✓ ЭКИПИРОВАНО</small><button onclick="unequipItemType(\''+k+'\')">Снять</button>'})};
  const extraShop=[{id:'r38helm',cat:'armor',type:'head',slot:'head',icon:'🪖',name:'Стальной шлем',desc:'+2 к защите',price:70,def:2},{id:'r38ring',cat:'armor',type:'ring',slot:'ring',icon:'💍',name:'Серебряное кольцо',desc:'+3% к криту',price:90,crit:.03},{id:'r38cloak',cat:'armor',type:'cloak',slot:'cloak',icon:'🧥',name:'Плащ странника',desc:'+1 к защите',price:60,def:1},{id:'r38boots',cat:'armor',type:'boots',slot:'boots',icon:'👢',name:'Сапоги пустоши',desc:'+1 к защите',price:55,def:1},{id:'r38amulet',cat:'armor',type:'amulet',slot:'amulet',icon:'🔮',name:'Амулет Бездны',desc:'+8 к максимуму энергии',price:110,maxEnergy:8},{id:'r38shield',cat:'armor',type:'shield',slot:'shield',icon:'🛡️',name:'Щит пепла',desc:'+3 к защите',price:120,def:3}];extraShop.forEach(x=>{if(!shopItems.some(y=>y.id===x.id))shopItems.push(x)});
  const __buyItem=buyItem; buyItem=function(id){const item=shopItems.find(x=>x.id===id);if(item&&['head','ring','boots','cloak','amulet','shield'].includes(item.type)){if(!inventoryHasSpace()||getGold()<item.price){sfx('error');return}hero.gold-=item.price;hero.items.push({...item});save();update();shopTab(shopCategory);logEvent('МАГАЗИН','Куплено: '+item.name+'.');return}return __buyItem.apply(this,arguments)};
  const __explore=explore; explore=function(){__explore.apply(this,arguments);if(enemy&&abyssFloor>=8){const f=1+(abyssFloor-7)*.25;enemy.max=Math.round(enemy.max*f);enemy.hp=enemy.max;enemy.attack=Math.round(enemy.attack*Math.pow(f,.55));enemy.def=Math.max(enemy.def,Math.floor((abyssFloor-7)*.8));updateBattle()}};
  const __cycleSetting=cycleSetting; cycleSetting=function(type,button){if(type==='language'){const v=localStorage.getItem('abyss_language')||'Русский';const n=v==='Русский'?'English':'Русский';localStorage.setItem('abyss_language',n);button.innerHTML='‹ '+n+' ›';document.documentElement.lang=n==='English'?'en':'ru';return}__cycleSetting.apply(this,arguments);if(type==='graphics'){const v=localStorage.getItem('abyss_graphics')||'Высокое';const g=el('game');if(g)g.dataset.graphics=v}};
  if(!document.getElementById('release-v38-style')){const st=document.createElement('style');st.id='release-v38-style';st.textContent='#game[data-graphics="Низкое"] .panel{box-shadow:none!important}#game[data-graphics="Среднее"] .panel{box-shadow:inset 0 0 6px rgba(130,0,0,.08),0 0 7px rgba(80,0,0,.1)}';document.head.appendChild(st)}
})();
